name: study_flash
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.0.0
  cupertino_icons: ^1.0.8
  flip_card: ^0.7.0
  fl_chart: ^1.1.1
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_database: ^12.1.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  rxdart: ^0.28.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  riverpod_generator: ^3.0.3
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  custom_lint: ^0.8.1
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
  assets:
    - lib/constants/images/
